#!/bin/bash
# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
$OPENSHIFT_REPO_DIR/pharo-server/st-exec.sh stop
exit 0
